# K-Nearest Neighbors

In [ ]:
import numpy as np
import pandas as od
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.datasets import load_iris

In [ ]:
# Loading the dataset
iris=load_iris()
X=iris.data # Features
y=iris.target # Target

# Splitting dataset into training and testing
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
# Normalize the features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
# KNN Classifier
knn=KNeighborsClassifier(n_neighbors=5)
# Train the model
knn.fit(X_train,y_train)
# Make predictions
y_pred=knn.predict(X_test)

# Evaluate the model
accuracy=accuracy_score(y_test,y_pred)
print(f"Accuracy:{accuracy:.2f}")
conf_matrix=confusion_matrix(y_test,y_pred)
print("Confusion Matrix:\n")
print(conf_matrix)
class_report=classification_report(y_test,y_pred)
print("Classification Report:\n")
print(class_report)

Accuracy:1.00
Confusion Matrix:

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

