# Naive Bayes Classifier

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn import datasets

In [2]:
# Loading the datset
iris=datasets.load_iris()
X=iris.data # features
y=iris.target # target

# Splitting the dataset
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)


In [3]:
# Naive Bayes Classifier
nb=GaussianNB()
# Training the model
nb.fit(X_train,y_train)
# Predicting
y_pred=nb.predict(X_test)

In [4]:
print("Accuracy: ",accuracy_score(y_test,y_pred))
# Confusion Matrix
print("Confusion Matrix: \n",confusion_matrix(y_test,y_pred))
# Classification Matrix
print("Classification Report: \n",classification_report(y_test,y_pred))

Accuracy:  1.0
Confusion Matrix: 
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

